### PR TITLE
Update 06-agutierrez689.md

### PR DESCRIPTION
**Pull request by agutierrez689**
TL;DR - Fix a Bug

##Title 2

fixes/resolves/closes/

To Do

[] fix a bug

cc:

### CODE REVIEW

**Review by vpham-training — COMMENTED** [review]
looks good

**Review by vpham-training — APPROVED** [review]
approved

**Review by ryan-ortiz — CHANGES_REQUESTED** [review]
I refuse to approve

**Review by Jarvis9494 — APPROVED** [review]

**Review by HappyFunNorm — APPROVED** [review]
good

**Review by jbryantpers — APPROVED** [review]
and then...

**Review by ryan-ortiz — APPROVED** [review]

**Comment by Jarvis9494** [comment]
Not good. yolo, let's test in production.

**Pull request merged**
